php api clean up after itself now updated config.guess

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -35069,10 +35069,14 @@ fi
 
 
 
+
+	MDBTOOLSINCLUDES=""
+	MDBTOOLSLIBS=""
+	MDBTOOLSLIBSPATH=""
+	MDBTOOLSSTATIC=""
+
 	if ( test -n "$GLIBINCLUDES" -a -n "$GLIBLIBS" )
 	then
-
-		MDBTOOLSSTATIC=""
 
 		if ( test "$cross_compiling" = "yes" )
 		then
@@ -36394,25 +36398,88 @@ then
 fi
 
 
-			if ( test -n "$MDBSQLINCLUDES" -a -n "$MDBSQLLIBS" -a -n "$MDBINCLUDES" -a -n "$MDBLIBS" )
+			if ( test -n "$MDBSQLINCLUDES" -o -n "$MDBSQLLIBS" -o -n "$MDBINCLUDES" -o -n "$MDBLIBS" )
 			then
+				LINKFAIL=""
 				MDBTOOLSINCLUDES="$MDBINCLUDES $MDBSQLINCLUDES $GLIBINCLUDES"
 				MDBTOOLSLIBS="$MDBSQLLIBS $MDBLIBS $GLIBLIBS"
-			fi
+				echo "$as_me:$LINENO: checking if MDB Tools has mdb_run_query" >&5
+echo $ECHO_N "checking if MDB Tools has mdb_run_query... $ECHO_C" >&6
 
+SAVECPPFLAGS="$CPPFLAGS"
+SAVELIBS="$LIBS"
+SAVE_LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
+CPPFLAGS="$MDBTOOLSINCLUDES"
+LIBS="$MDBTOOLSLIBS $SOCKETLIB $DLLIB -lm"
+LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
+export LD_LIBRARY_PATH
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <mdbsql.h>
+#include <stdlib.h>
+int
+main ()
+{
+mdb_run_query(NULL,NULL);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6;
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_MDB_RUN_QUERY 1
+_ACEOF
 
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
 
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; LINKFAIL="yes"
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+CPPFLAGS="$SAVECPPFLAGS"
+LIBS="$SAVELIBS"
+LD_LIBRARY_PATH="$SAVE_LD_LIBRARY_PATH"
+export LD_LIBRARY_PATH
 
-
-
-			if ( test -z "$MDBTOOLSLIBS" )
-			then
-				{ echo "$as_me:$LINENO: WARNING: MDB Tools support will not be built." >&5
-echo "$as_me: WARNING: MDB Tools support will not be built." >&2;}
 			fi
 
 		fi
 
+		if ( test -z "$MDBTOOLSLIBS" -o -n "$LINKFAIL" )
+		then
+			{ echo "$as_me:$LINENO: WARNING: MDB Tools support will not be built." >&5
+echo "$as_me: WARNING: MDB Tools support will not be built." >&2;}
+		fi
 	fi
 
 
@@ -36426,6 +36493,11 @@ if ( test -n "$MDBTOOLSLIBS" )
 then
 	echo "mdbtools libs... $MDBTOOLSLIBS"
 fi
+
+
+
+
+
 
 fi
 
@@ -40686,7 +40758,7 @@ RPM_BUILD_DIR=`rpm --eval "%_topdir" 2>/dev/null`
 
 
 
-SQLR_VERSION="0.35.1"
+SQLR_VERSION="0.36"
 
 
 cat >>confdefs.h <<_ACEOF
