modified it so it would work

diff --git a/init/slackware/rc.d/rc.sqlrelay.in b/init/slackware/rc.d/rc.sqlrelay.in
--- a/init/slackware/rc.d/rc.sqlrelay.in
+++ b/init/slackware/rc.d/rc.sqlrelay.in
@@ -26,13 +26,13 @@ start(){
             echo -n $"Launching instance with id '${connid}':"
             sqlr-start -id ${connid} >/dev/null 2>&1
             RETVAL=$?
-            [ $RETVAL -eq 0 ] && success || failure
+            [ $RETVAL -eq 0 ] && echo "success" || echo "failure"
             launched=1
         done
-        [ "$launched" -eq 1 ] || passed
+        [ "$launched" -eq 1 ] || echo "passed"
         echo
     else
-        failure
+        echo "failure"
     fi
     [ $RETVAL -eq 0 ] && touch /var/lock/subsys/sqlrelay
     return $RETVAL
@@ -42,7 +42,7 @@ stop(){
     echo -n $"Stopping SQL Relay: "
     sqlr-stop >/dev/null 2>&1
     RETVAL=$?
-    [ $RETVAL -eq 0 ] && success || failure
+    [ $RETVAL -eq 0 ] && echo "success" || echo "failure"
     echo
     [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/sqlrelay
     return $RETVAL
