cygwin compatibility fixes

diff --git a/src/api/perl/Connection/Makefile b/src/api/perl/Connection/Makefile
--- a/src/api/perl/Connection/Makefile
+++ b/src/api/perl/Connection/Makefile
@@ -4,6 +4,7 @@ include ../../../../config.mk
 
 PERLCCFLAGS = $(DESTDIR)$(shell eval "`$(PERL) -V:ccflags`"; export ccflags; echo $$ccflags | sed -e 's| -belf||g' -e 's| -KPIC||g' -e 's| -xdepend||g' -e 's| -x03||g' -e "s|UNKNOWN||g" )
 PERLOPTIMIZE = $(DESTDIR)$(shell eval "`$(PERL) -V:optimize`"; export optimize; echo $$optimize | sed -e 's| -belf||g' -e 's| -KPIC||g' -e 's| -xdepend||g' -e 's| -x03||g' -e "s|UNKNOWN||g" )
+PERLINSTALLARCHLIB = $(DESTDIR)$(shell eval "`$(PERL) -V:installarchlib`"; export installarchlib; echo $$installarchlib | sed -e "s|UNKNOWN||g" )
 PERLSITEARCH = $(DESTDIR)$(shell eval "`$(PERL) -V:sitearch`"; export sitearch; echo $$sitearch | sed -e "s|UNKNOWN||g" )
 PERL_INC = $(DESTDIR)$(shell eval "`$(PERL) -V:archlibexp`"; export archlibexp; echo "-I$$archlibexp/CORE" | sed -e "s|UNKNOWN||g" )
 PERL_LIB = $(DESTDIR)$(shell eval "`$(PERL) -V:privlibexp`"; export privlibexp; echo $$privlibexp | sed -e "s|UNKNOWN||g" )
@@ -11,7 +12,7 @@ PERLINSTALLMAN3DIR = $(DESTDIR)$(shell eval "`$(PERL) -V:installman3dir`"; expor
 PERLMAN3EXT = $(shell eval "`$(PERL) -V:man3ext`"; export man3ext; echo $$man3ext | sed -e "s|UNKNOWN||g" )
 
 CPPFLAGS = $(BASECPPFLAGS) $(PERLOPTIMIZE) $(PERLCCFLAGS) -I./ -I$(top_builddir) -I$(top_builddir)/src/api/c++/include $(RUDIMENTSINCLUDES) $(PERL_INC)
-LIBS = -L$(top_builddir)/src/api/c++/src -lsqlrclient $(RUDIMENTSLIBS) $(LIBDMALLOC) $(LIBEFENCE)
+LIBS = $(PERLLIB) -L$(top_builddir)/src/api/c++/src -lsqlrclient $(RUDIMENTSLIBS) $(LIBDMALLOC) $(LIBEFENCE)
 RPATH =
 ifneq ($(strip $(libdir)),)
 ifeq ($(PERLUSERPATH),yes)
@@ -31,19 +32,28 @@ endif
 		cp perlincludes2.h perlincludes.h; \
 		$(LIBTOOL) --mode=compile $(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@ 2> errors2; \
 		if ( test ! -r Connection.lo ); then \
-			cp perlincludes2.h perlincludes.h; \
+			cp perlincludes3.h perlincludes.h; \
 			$(LIBTOOL) --mode=compile $(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@ 2> errors3; \
 			if ( test ! -r Connection.lo ); then \
-				if ( test -s errors1 ); then \
-					echo "first try errors : "; cat errors1; echo; \
-				fi; \
-				if ( test -s errors2 ); then \
-					echo "second try errors : "; cat errors2; echo; \
-				fi; \
-				if ( test -s errors3 ); then \
-					echo "third try errors : "; cat errors3; echo; \
-				fi; \
-				exit 1; \
+				cp perlincludes4.h perlincludes.h; \
+				$(LIBTOOL) --mode=compile $(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@ 2> errors4; \
+				if ( test ! -r Connection.lo ); then \
+					if ( test -s errors1 ); then \
+						echo "first try errors : "; cat errors1; echo; \
+					fi; \
+					if ( test -s errors2 ); then \
+						echo "second try errors : "; cat errors2; echo; \
+					fi; \
+					if ( test -s errors3 ); then \
+						echo "third try errors : "; cat errors3; echo; \
+					fi; \
+					if ( test -s errors4 ); then \
+						echo "fourth try errors : "; cat errors4; echo; \
+					fi; \
+					exit 1; \
+				else \
+					cat errors4; \
+					$(STRIPCOMMENTNOTE) $@; \
 			else \
 				cat errors3; \
 				$(STRIPCOMMENTNOTE) $@; \
@@ -56,7 +66,7 @@ endif
 		cat errors1; \
 		$(STRIPCOMMENTNOTE) $@; \
 	fi; \
-	$(RM) errors1 errors2 errors3 perlincludes.h
+	$(RM) errors1 errors2 errors3 errors4 perlincludes.h
 
 
 all: libConnection.la
@@ -74,7 +84,7 @@ clean:
 rebuild: clean all
 
 libConnection.la: Connection.xs Connection.C Connection.lo
-	$(LIBTOOL) --mode=link $(CXX) -o $@ Connection.lo $(LIBS) -rpath $(PERLSITEARCH)/auto/SQLRelay/Connection $(RPATH) -module -no-undefined
+	$(LIBTOOL) --mode=link $(CXX) -o $@ Connection.lo -rpath $(PERLSITEARCH)/auto/SQLRelay/Connection $(RPATH) -module -no-undefined $(LIBS)
 
 Connection.so:
 	if ( test -r .libs/libConnection.0.0.0 ); \
